server:
  port: 8081

topic:
  name: dima.dima.dima

spring:
  kafka:
    consumer:
      group-id: "default"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password: dev